### ISSUE TITLE
Expected Scenario for Server Deployment?

### ISSUE THREAD

**Issue by johnzimm** [conveyal/trimet-mod-otp#1]
Looking at the README there are some steps documented for running this with the webpack development server locally.

Do you have expected steps/scenarios available to add to the README for deployment to a server or a production deployment scenario?  In TriMet's scenarios we would be looking for static file generation to be served by Apache or to run a nodejs server via PM2 to proxy behind Apache.

Also looking to be able to configure the project to have a configureable base path (not just a default route).

e.g. https://ride.trimet.org/<some_configurable_path>/<app_here>

**Comment by johnzimm** [comment]
Including snippet from slack thread for more context: 

> demory [Jun 22nd at 10:49 AM] 
> in #general
> @fpurcell, the way we're deploying the front-end for demo/test purposes, it's just static assets generated by webpack
> 
> jzimm [1 month ago] 
> demory: Sorry.  Just catching up on this thread.  We have gotten trimet-mod-otp running locally via webpack for testing purposes...  Can you update the README in that project explaining all the requirements for build, services it relies on, and what the expected deployment looks like in a production scenario?  We will ultimately be deploying with all components hosted on our own infrastructure.  OTP, Pelias, Modeify, trimet-mod-otp, etc....  It appears that Modeify is the middleware component we were wondering about a couple months back.


Also we want to verify that Modeify and all of its dependencies are required?

**Comment by fpurcell** [comment]
Going to close this, since we now have deployment  and the paths that John mentions solved
