### ISSUE TITLE
Presentation Consistency: Stop Bubbles, Stop Viewer, Start/End Markers

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#103]
**Desktop**
1.  On the map, in the itinerary, and in the stop bubble, the start (origin) is an orange map marker and the end (destination) is a green target.  However, in the stop viewer, the start (from here) is a target and the destination (to here) is a map marker (both black).  Can they all match?

2.  In the stop bubble we say 'Set as: Start | End' and in the Stop Viewer we say 'Plan a trip: From here | To here'.  Please use the 'Plan a trip' version in the Stop Viewer.

![croppercapture 275](https://user-images.githubusercontent.com/4853348/46168574-b7fece80-c24d-11e8-8a5a-7c8d96af4e2c.png)

**Mobile**
1.  Once a trip is planned, the markers in the origin/destination fields at the top of the screen are still the star (origin) and map marker (destination; both black).  Please change to the orange map marker for the origin and the green target for the destination.

![croppercapture 277](https://user-images.githubusercontent.com/4853348/46170142-d8308c80-c251-11e8-85dc-faad12bc4de1.png)

2.  The stop bubble in mobile has only the plan trip options; does not display stop name, etc.  Can it match what is used in the desktop version?  (Okay to scale in mobile if pop-up ever greater than 4 lines though)
 
![croppercapture 276](https://user-images.githubusercontent.com/4853348/46169717-bbe02000-c250-11e8-8026-a875b16bde46.png)

**Mobile & Desktop**
Please amend the stop bubble layout to more efficiently utilize the space (and in anticipation of incorporating more than one agency (and at least two sharing the same location)).  Suggested layout:

 
![croppercapture 279](https://user-images.githubusercontent.com/4853348/46177509-ea1d2a00-c267-11e8-8037-c021862372eb.png)

**Comment by msrichardson** [comment]
re: Mobile #2, ah, that makes sense.  Thanks.

**Comment by landonreed** [comment]
Regarding the Mobile/Desktop item (stop bubble layout), I don't know this for sure, but I don't think OpenTripPlanner merges stop entities from more than one agency together. In other words, there would never be a stop that you can click that would show multiple stop IDs (nor multiple agencies).

As we add other GTFS feeds we may run into cases where multiple stops are sitting on top of one another. There isn't an immediate solution that comes to mind for this issue.

**Comment by msrichardson** [comment]
All items resolved except the mobile & desktop item (per comment from ~Oct 4).  Will open new ticket if that item becomes an issue in the future.
