### ISSUE TITLE
Park & Rides overlay

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#109]
This has partially been discussed/broached in Slack; adding here "for the record"

There are some Park & Rides that are in OSM but are not displaying on the map when the Park & Ride layer is activated.  

Gateway Park & Ride is a good example.  I should be located approximately where the black arrow is pointing near the middle of the screenshot below.  (issue continues below screenshot)

![croppercapture 292](https://user-images.githubusercontent.com/4853348/46426564-cb99b180-c6f3-11e8-8526-7e9571c55b26.png)

https://www.openstreetmap.org/way/109719588

There are at least two other parking structures that aren't showing (Hatfield and Gresham), so initially thought maybe that was the issue (garage v surface lot), but found there is also at least one surface lot that isn't displaying - Hall/Nimbus (should be in the general vicinity of hte yellow area in screenshot below).

![croppercapture 295](https://user-images.githubusercontent.com/4853348/46427437-4bc11680-c6f6-11e8-8e94-cf6508d0643e.png)

https://www.openstreetmap.org/way/417811681

**Comment by landonreed** [comment]
According to the graph build logs, Gateway Park & Ride (and a few others) appear to be coded incorrectly in OSM, which means they are not processed for use by OTP.  Here's a snippet of those logs:

```
14:30:56.336 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R Gresham Parking Garage' (258685823) not linked to any streets; it will not be usable.
14:30:56.336 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R Hillsboro Park & Ride' (30298951) not linked to any streets; it will not be usable.
14:30:56.337 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R Hall/Nimbus Park and Ride' (417811681) not linked to any streets; it will not be usable.
14:30:56.338 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R Intermodal Transit Facility' (331149268) not linked to any streets; it will not be usable.
14:30:56.339 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R' (529563444) not linked to any streets; it will not be usable.
14:30:56.340 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R' (561400397) not linked to any streets; it will not be usable.
14:30:56.340 WARN (OpenStreetMapModule.java:521) Park and ride 'P+R Gateway Park & Ride' (109719588) not linked to any streets; it will not be usable.
```

There may be other P&Rs not linked (the OSM network I used may be smaller than the actual bounds we're using for the trip planner).

**Comment by msrichardson** [comment]
Thanks, we'll look into that further on our end.

**Comment by landonreed** [comment]
I've just made an OSM change to the Gateway P&R that should fix the issue: https://www.openstreetmap.org/changeset/63170763

You could use this changeset as an example when making further edits.

**Comment by msrichardson** [comment]
We've updated those Park & Rides in OSM, would it be possible to do a refresh on your end to help verify it worked/resolved the issue?
