### ISSUE TITLE
Printing Itineraries

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#117]
There are issues with actually printing for all four Windows browsers, and Safari.

**Chrome, Firefox, and Safari:**  Only prints one page, which is problematic for longer trips.  Even with relatively short trips, the Trip Details and/or part of the directions are cut off.  (For the Firefox example, the actual paper printout is slightly worse than the PDF version.)

[TriMet MOD OTP Demo_Chrome.pdf](https://github.com/conveyal/trimet-mod-otp/files/2470826/TriMet.MOD.OTP.Demo_Chrome.pdf)
[TriMet MOD OTP Demo_Chrome2.pdf](https://github.com/conveyal/trimet-mod-otp/files/2470827/TriMet.MOD.OTP.Demo_Chrome2.pdf)  [Longer trip]
[TriMet MOD OTP Demo_Firefox.pdf](https://github.com/conveyal/trimet-mod-otp/files/2470828/TriMet.MOD.OTP.Demo_Firefox.pdf)
[TriMet MOD OTP Demo_Safari.pdf](https://github.com/conveyal/trimet-mod-otp/files/2471028/TriMet.MOD.OTP.Demo_Safari.pdf)

**Edge and IE**:  Essentially prints a blank page (Edge is wholly blank, while IE has headers/footers)

[TriMet MOD OTP Demo_Edge.pdf](https://github.com/conveyal/trimet-mod-otp/files/2470835/TriMet.MOD.OTP.Demo_Edge.pdf)
[TriMet MOD OTP Demo_IE.pdf](https://github.com/conveyal/trimet-mod-otp/files/2470836/TriMet.MOD.OTP.Demo_IE.pdf)

**Comment by landonreed** [comment]
Ah, it looks like changes we made related to #92 have caused this issue. I will work on a fix.

**Comment by landonreed** [comment]
@msrichardson, the fixes I just pushed should solve this issue.
