### ISSUE TITLE
Allow display of time in 12- or 24-hour mode

### ISSUE THREAD

**Issue by demory** [conveyal/trimet-mod-otp#121]
Currently time is displayed in 24-hour in in certain places. Make the default time format configurable.

![image](https://user-images.githubusercontent.com/653100/47233355-5088fa00-d387-11e8-9c72-31ddd804b9a8.png)

**Comment by msrichardson** [comment]
Please be sure the print view is also consistent with the rest of the app (currently uses 24-hr time).

![croppercapture 357](https://user-images.githubusercontent.com/4853348/52308697-d76fdb80-2952-11e9-8e68-2cd67803d23d.png)
