### ISSUE TITLE
Mode for last leg doesn't always display

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#151]
This could possibly be a function of the length of the trip, but in the sample below, the text version of the itinerary and the print both do not indicate how one gets from the final transit stop to the destination.  If one zooms to that location on the map, it appears to use rideshare.

SEARCH DATA:
Address: https://modbeta.trimet.org/map/#/?fromPlace=2702%2023rd%20Pl%2C%20Forest%20Grove%2C%20OR%2C%20USA%2097116%3A%3A45.524630364755254%2C-123.09906005859376&toPlace=25850%20S%20River%20Lake%20Rd%2C%20Clackamas%20County%2C%20OR%2C%20USA%2097023%3A%3A45.28252647040787%2C-122.33551025390626&date=2018-12-17&time=12%3A59&arriveBy=false&mode=TRAM%2CRAIL%2CGONDOLA%2CBUS%2CCAR_HAIL&showIntermediateStops=true&optimize=QUICK&ignoreRealtimeUpdates=true&companies=LYFT&minTransitDistance=50%25&searchTimeout=10000
Browser: Firefox 60.0
OS: Windows 7

![croppercapture 348](https://user-images.githubusercontent.com/4853348/50456781-b8ba0600-090b-11e9-9f92-434485c517a7.png)

![croppercapture 349](https://user-images.githubusercontent.com/4853348/50456780-b8216f80-090b-11e9-8375-12ae3f311659.png)

![croppercapture 350](https://user-images.githubusercontent.com/4853348/50456779-b8216f80-090b-11e9-81d4-ec07b3ff02b0.png)

**Comment by evansiroky** [comment]
A fix is incoming for this issue via https://github.com/opentripplanner/OpenTripPlanner/commit/476d14dcb98a2293a2fd857a51546190fd0c85c4.

**Comment by msrichardson** [comment]
With the changes made to accommodate this issue, please also change the text of the resultant error message to "Sorry, we couldn't find any transit or rideshare/carshare options at the time and/or location you chose. Please try again later, or change the settings of your trip."

Current message for reference:
![image 1](https://user-images.githubusercontent.com/4853348/53740037-19a01600-3e48-11e9-93f0-bc3892099fde.png)
