### ISSUE TITLE
BIKETOWN Facility Labels

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#152]
It looks like when BIKETOWN is used in an itinerary, the start/end points (at least when corrals) are labeled twice.

![croppercapture 352](https://user-images.githubusercontent.com/4853348/51056834-c1137180-1598-11e9-9689-2b4f65d55b11.png)

**Comment by landonreed** [comment]
This looks to be not a direct issue with [transitive.js](https://github.com/conveyal/transitive.js), but rather the function that converts an itinerary to the transitive data structure. The bike rental station looks to be labeled twice, as a from place and a to place:

https://github.com/opentripplanner/otp-react-redux/blame/trimet-dev/lib/util/map.js#L79-L84
