### ISSUE TITLE
Itinerary Options 2 & 3 shouldn't show when exact matches of Option 1

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#154]
Usually, when itinerary options 2 and 3 exactly match option 1, they are not shown, however we found an instance where they are.

https://trimet-mod-dev.conveyal.com/#/?fromPlace=%28Current%20Location%29%3A%3A45.532046199999996%2C-122.6037914&toPlace=TriMet%20Administration%20Headquarters%2C%20Portland%2C%20OR%2C%20USA%3A%3A45.510172%2C-122.677488&date=2019-02-07&time=13%3A30&arriveBy=true&mode=WALK%2CBUS%2CTRAM%2CRAIL%2CGONDOLA&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=NaN

**Comment by msrichardson** [comment]
Upon further testing, it appears that _all_ trip plans (at least that are walk+transit) are showing the same results for options 1-3.

**Comment by fpurcell** [comment]
I'm seeing different results for Myleen's trip with an older version of OTP:

https://modbeta.trimet.org/map/#/?fromPlace=NE_60th%3A%3A45.53204%2C-122.6037&toPlace=TriMet%3A%3A45.510172%2C-122.677488&date=2019-02-07&time=13%3A30&arriveBy=true

(see https://maps.trimet.org/m/otp.v for version and gtfs info)

vs.

https://trimet-mod-dev.conveyal.com/#/?fromPlace=NE_60th%3A%3A45.53204%2C-122.6037&toPlace=TriMet%3A%3A45.510172%2C-122.677488&date=2019-02-07&time=13%3A30&arriveBy=true

**Comment by msrichardson** [comment]
The app is no longer showing the same results for options 1-3 for all trip plans.  Will keep this open for time being to continue testing initial entry.
