### ISSUE TITLE
Elevation displays

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#171]
Please make the following changes in regards to the elevation displays  (please break apart ticket as needed, and inform if any requests are not feasible):

1. Reduce size of preview and add header, such as Elevation Chart or Elevation Profile.  Either make entire item a button or make header a clickable link (basically, make it obvious that it is clickable and something will happen upon doing so).  Example:

![SmallPreview](https://user-images.githubusercontent.com/4853348/55436383-feace880-5550-11e9-83f2-c479284c2ac7.PNG)

2. In current expanded version, not all streets are labeled (sometimes due to very short segments).  Please remove the existing labels and have street names appear when hovering over applicable segment, similar to ride.trimet.org (presume would appear within profile, but open to other options, such as below (where current labels are now).  
--If unable to do both this and also display elevation, please only do this.
--Here is example from ride.trimet.org:  
![rideexample](https://user-images.githubusercontent.com/4853348/55436671-cb1e8e00-5551-11e9-904c-e1159159d841.PNG)

3.  Scale horizontally to fit screen when in expanded mode.

4.  If keep actual elevation (as move along profile, see #2 above), then please round to nearest foot due to data resolution.

**Comment by fpurcell** [comment]
IMPORTANT:  also add a switch in config.yml so that we can easily turn on & off all elevation graphs.
