### ISSUE TITLE
Route Geometry between Nearby Stops is Broken

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#18]
The geometry across a bridge between two stops is going in a straight line.  Looks bad when it should go across a bridge:

![Stright Line Geo](https://user-images.githubusercontent.com/64323/31035510-2508a22a-a51d-11e7-9299-87a425810000.png)

vs.

![Conforms to Brige Geo](https://user-images.githubusercontent.com/64323/31035542-3cde8964-a51d-11e7-9d3a-22fd7726bfe6.png)

**Comment by demory** [comment]
This is a known bug with the transitive library that is being resolved

**Comment by demory** [comment]
Fixed in https://github.com/conveyal/transitive.js/commit/da5320f86694071c562f5f00295ad1231a7dbed5

**Comment by msrichardson** [comment]
This issue has been resolved in the 20180209 update.
