### ISSUE TITLE
Map Style: Show / Hide Route Numbers

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#19]
We'll never want to render "291" labels.  That is a late-night route w/2 trips.  Geometry itself is okay, but no "291" label.   (I'm sure they'll be other labels we show / hide / customize ... MAX/WES/SC/TRAM for example ... those labels will probably come from a config file, and relate to GTFS via route id).

![Route 291 Label](https://user-images.githubusercontent.com/64323/31035755-035e1bb8-a51e-11e7-8e84-f6470b834fc3.png)

**Comment by demory** [comment]
To be resolved in gtfs-tiler library

**Comment by fpurcell** [comment]
We don't use this overlay, so closing...
