### ISSUE TITLE
Configure Pelias Path

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#2]
I'd like to change the path to TriMet's instance of Pelias via config.yml.   (BTW, keep the api_key option ... I may use that later).

**Comment by fpurcell** [comment]
BTW, I can see that a few items and attributes in this component will need to be configurable: https://github.com/conveyal/isomorphic-mapzen-search/blob/master/index.js

All of these might need to be configurable:
const mapzenUrl = 'https://search.mapzen.com/v1'
const searchUrl = `${mapzenUrl}/search`
const autocompleteUrl = `${mapzenUrl}/autocomplete`
 @param  {string} [$0.sources='gn,oa,osm,wof']

About the above:
- base mapzen URL is obvious.
- For TriMet, it's possible that search & autocomplete URLs might point to the same 'search' service.
- Sources might include a new 'transit' source in Pelias (e.g., stops, P&Rs, TCs, stations, etc...)  -- see https://github.com/OpenTransitTools/pelias.transit.loader

**Comment by demory** [comment]
@fpurcell: This has been completed by @landonreed, just waiting for endpoint to plug in.
