### ISSUE TITLE
BUG (High): Map Click Origin/Destination Select 

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#21]
Double Click is a defacto map zoom control.  Don't put down origin / destination calipers when double clicking the map.  Detect double clicks and click-and move map, and don't place calipers on those common map manipulations.  

![Double Click](https://user-images.githubusercontent.com/64323/31035959-f26ad246-a51e-11e7-8386-facdd4d363d7.png)

**Comment by fpurcell** [comment]
Tap & Hold Idea from Dave Whipple

For one, it assumes the user wants to select a destination when they simply tap somewhere on the map while dragging/exploring, which could easily result in unexpected behavior for the user if that wasn’t their intent. It also interferes with standard map gestures, such as double-tapping/double-clicking to zoom in. It could end up being a pretty clumsy way to select a location because you need to drag and zoom considerably before you can select a location with any level of accuracy, and the chance of errors is high. (It’s likely going to be a point of frustration as users try and fail to get the location they really want, or accidentally set a location when they didn’t mean to.) If we want to provide a method for selecting a location besides current location, nearby/favorites/recents and typing an address, we would suggest instead doing this Uber/Lyft/Transit App style -- that is, by dragging the map around while a fixed center point serves as the selector. This way it doesn’t interfere with existing map gestures, and takes advantage of the established and familiar gesture of simply dragging the map to explore. And more important, instead of being on by default, perhaps this mode is triggered by tapping a link in the location selection dropdown pane after tapping in the omnibox field -- something like “Select location on map”. Other options to  consider include a right-click on desktop (current behavior on ride.trimet.org) as well as tap-and-hold on mobile. (Tap-and-hold could be promising!)

**Comment by fpurcell** [comment]
Center Point Select from Dave Whipple

We would suggest instead doing this Uber/Lyft/Transit App style -- that is, by dragging the map around while a fixed center point serves as the selector. This way it doesn’t interfere with existing map gestures, and takes advantage of the established and familiar gesture of simply dragging the map to explore. And more important, instead of being on by default, perhaps this mode is triggered by tapping a link in the location selection dropdown pane after tapping in the omnibox field -- something like “Select location on map”.

**Comment by fpurcell** [comment]
IDEA: Tap and Hold Select from Dave

Other options to  consider include a right-click on desktop (current behavior on ride.trimet.org) as well as tap-and-hold on mobile. (Tap-and-hold could be promising!)

**Comment by demory** [comment]
After internal discussion we are inclined to go the right-click (desktop) / long-tap (mobile) route. This would bring up a selection menu/popup perhaps similar to the CarFreeAtoZ interface:
![image](https://user-images.githubusercontent.com/653100/31906144-552f133c-b7fe-11e7-8726-0d1d413e1628.png)

**Comment by fpurcell** [comment]
RE-OPEN: mobile not resolved - when first opened on iphone, first click is to destination

**Comment by fpurcell** [comment]
On Mobile, the first time you touch the map, it becomes an origin click ... that first map click is not a press and hold action.

**Comment by demory** [comment]
Addressed in https://github.com/opentripplanner/otp-react-redux/commit/dd2c71b2d8c3b4839ce238e4858696de87cfcbc4

Map click action on the mobile welcome screen is no longer overridden so double-click-to-zoom should be preserved. To select a location, a long tap will bring up the selection popup for choosing a from/to location:

![image](https://user-images.githubusercontent.com/653100/36029511-50c3ace0-0d58-11e8-8b73-f128a6d047a3.png)

After the user selects 'from' or 'to', the auto-detected current location will be used as the other endpoint.

**Comment by msrichardson** [comment]
Mobile has been resolved with the 20180209 update.
