### ISSUE TITLE
DESIGN: use circle for Origin icon (not a star)

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#23]
We suggest using a _circle_ (or other icon) to indicate TO location instead of _star_, mainly because a star is commonly used to indicate favorites.  

![Circle Icon Mockup](https://user-images.githubusercontent.com/64323/31239154-02e03846-a9b1-11e7-8783-8af4b0fa55d1.png)

**Comment by demory** [comment]
We had some concern that a simple hollow circle would be confused with transit stops/transfers:
![image](https://user-images.githubusercontent.com/653100/31906593-79f42120-b7ff-11e7-92ab-3d64c0c1259d.png)

We propose using the "target" icon from font awesome as the start:
![image](https://user-images.githubusercontent.com/653100/31906633-96ecfe3c-b7ff-11e7-910e-184d2e2999d4.png)

**Comment by fpurcell** [comment]
Yeah, the target looks like it will fit the bill.  (BTW, I created all of the 'DESIGN' tickets seen here based off of Dave Whipple's feedback posted to Slack ... I was hoping make each point an individual task, and get with Dave & team to label which tasks were important and which could be thrown away;  that kinda happened, but we didn't get too far down the list;  fwiw, the circle start point was one we hit and was important -- no one like the start).

**Comment by fpurcell** [comment]
BTW, as of 1/30/18, there's still inconstant use of the star icon thru-out the app. Right click on the map, the dot-circle is in a map popup for placing a point. But place the actual point, and a star icon is used. The star icon is also still used in some stop popups / stop-left-nav views.

BTW, might be good to make this icon (and it's hot-spot) configurable via config.yml.

**Comment by msrichardson** [comment]
Also see #103

**Comment by msrichardson** [comment]
I am marking this as closed.  Can reopen if need to revisit.
