### ISSUE TITLE
DESIGN: don't allow customer to assign from & to the same value (or same / nearly same coord)

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#28]
Suggest some validation to avoid user setting both To and From to current location.
See #27

**Comment by msrichardson** [comment]
Testing on 1/17/18 found that if one inadvertently sets origin and destination to same location (on the desktop) version, it 'hung' (that is, was stuck in the mobile equivalent of 'WAITING' as opposed to timing out and displaying error).

Testing on 1/19/18 found that it displayed this error:
![croppercapture 70](https://user-images.githubusercontent.com/4853348/35173296-d03e6d82-fd1f-11e7-81e3-30837680768b.png)

**Comment by demory** [comment]
Improved error display now looks like this on trivially-close start/end points:

![image](https://user-images.githubusercontent.com/653100/36029395-dd625cce-0d57-11e8-91fe-2307da460300.png)

Is this sufficient?

**Comment by msrichardson** [comment]
Yes, this is sufficient.  Thank you.
