### ISSUE TITLE
IDEA: Pelias and Lat / Lon coordinates

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#3]
If the UI is permitted to use a customer's location, those lat and lon coords should probably be sent on to all subsequent geocoder calls via the focus.point.lat=46.5&focus.point.lon=-122.6 params.  

Those focus points are what Pelias uses to sort search results.  We're going to define default coords (downtown Portland) on the server ... but if a customer gives permission to use their coordinates, sorting geocoder results local to them can only make things better.  (e.g., in the 60 mile diameter between Vancouver WA and Salem OR, I'm guessing their are at least ten "Main Streets").

**Comment by landonreed** [comment]
@fpurcell, I think we're on board with this idea.  Thanks for the suggestion!

**Comment by fpurcell** [comment]
done
