### ISSUE TITLE
checkmark icons need to be changed from red to green -- (was DESIGN: large mode buttons (and a bit of text))

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#31]
For this UI we propose large mashable buttons that are easy to identify and easy to tap/click, with room for text labels so that these somewhat ambiguous icons can be easily distinguished from one another at a glance.

![fat buttons](https://user-images.githubusercontent.com/64323/31257317-d6d616e4-a9ec-11e7-98b2-b1481ceb0a1b.png)

**Comment by fpurcell** [comment]
Big Date & Time buttons...




- big, easy-to-find-and-tap buttons here for this UI, similar to above recommendation for Modes. “NOW” alone doesn’t indicate what options the user has unless they take further action to poke around the interface. 
- Plus there are only three options (two if you combine depart/arrive), so it’s probably not worthy of a dropdown. See mockup of possible UI approach at right.  
![fat date time](https://user-images.githubusercontent.com/64323/31257441-651c079c-a9ed-11e7-9eb3-a1eb8dd5c0ac.png)

**Comment by fpurcell** [comment]
- Question about Arrive-by: is this option still worth including in the trip planner? It has long been a buggy feature that results in some wacky trip plans… Will this OTP upgrade improve any arrive-by trips?

**Comment by demory** [comment]
Addressed in https://github.com/opentripplanner/otp-react-redux/commit/fe7e56351aa3e1007194fa5070878c7d681b5fbf and https://github.com/conveyal/trimet-mod-otp/commit/b7889452f555a37ffd49a0690320feb7be404605

**Comment by msrichardson** [comment]
Re: new mode buttons - can the fill of the checkmark icons please be changed from red to green?   This is a medium-low priority.
