### ISSUE TITLE
BUG: iPhone rotate screws up map and input forms...

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#33]
(Similar issue on desktop #32)

1. Start with this view: 
![iinitial view](https://user-images.githubusercontent.com/64323/31258017-004504dc-a9f1-11e7-9a4b-a1f3180031bf.png)

2. Rotate phone to Landscape view ... bye bye map:
![Landscape rotate phone, and map is gone](https://user-images.githubusercontent.com/64323/31258052-411b5a9c-a9f1-11e7-866d-c416f3ee53ef.png)

3. Rotate phone again, and still no map (and forms no longer work):
![No map & forms](https://user-images.githubusercontent.com/64323/31258045-28d12cdc-a9f1-11e7-8700-6df385c04d9d.PNG)

**Comment by demory** [comment]
Should be fixed now. I don't have an iPhone to confirm but the iPhone emulator in Safari appears to work correctly in landscape mode:

![image](https://user-images.githubusercontent.com/653100/36029195-18afb6c4-0d57-11e8-9583-88fa6641448d.png)

**Comment by fpurcell** [comment]
I'm leaving this open ... I've been seeing strangeness on recent versions of the app (last Friday June 1st 2018, I saw the geometry not align with the map in a huddle room PC using FF).  @demory @mosteele @msrichardson can you guys test and confirm whether this is still an issue?

**Comment by mosteele** [comment]
Didn't we decide that we wanted to not allow rotation? Is this feasible?

**Comment by fpurcell** [comment]
Not sure (not sure you can really block rotation ... and when rotating, if you don't rescale the app, there will be a lot of grey space).

Anyway, good news is that this isn't happening for me anymore on the iPhone. So will close...
