### ISSUE TITLE
BUG: switching between Map View & Network View, then scaling leads to problematic map rendering

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#34]
The mapped itinerary gets lost when you first view the Network View, then switch back to the Map then scale the map out.   (I've seen the same issues on mobile and desktop).

1. Show itinerary on map:
![Map Itinerary is Good](https://user-images.githubusercontent.com/64323/31258244-b0ec1cac-a9f2-11e7-8a54-cd5dc55fe435.png)

2. Switch to Network View (still okay):
![Network View .. still okay](https://user-images.githubusercontent.com/64323/31258316-33b493c6-a9f3-11e7-9c51-6cdbb7f1b381.png)

3. Switch back to Map, and Zoom the map out ... geometry is now broken.  (note the geometry is now at the bottom left of the map.  Zoom around further, and the geometry disappears):
![Back to map view and geometry is broken](https://user-images.githubusercontent.com/64323/31258333-4c92f09a-a9f3-11e7-9ce7-351b5ad52495.png)

**Comment by demory** [comment]
Should be fixed by https://github.com/opentripplanner/otp-react-redux/commit/cd28195f2cb4bac7f1a8fa785430145b6ecdd6f8
