### ISSUE TITLE
DESIGN: rounded input forms

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#35]
"We’d prefer using the TriMet style for the design of the form fields: See mockup below"

![roundedinputs](https://user-images.githubusercontent.com/64323/31264181-363c5790-aa1c-11e7-9f9d-3a702ab71fbc.png)

vs.

![boxinputs](https://user-images.githubusercontent.com/64323/31264184-3cc64792-aa1c-11e7-935c-c422d47c7a3b.png)

**Comment by fpurcell** [comment]
The clear form 'X' shouldn’t be visible until there is something entered into the form field.

**Comment by landonreed** [comment]
For reference here is the current mobile form view 
![image](https://user-images.githubusercontent.com/2370911/32116773-053bbb68-bb1a-11e7-9be7-b1be880b3ff4.png)

**Comment by fpurcell** [comment]
Will close for now to avoid noise. Will figure out for trimet.org to give desired look to forms.
