### ISSUE TITLE
UI: Modes and Walk Distance

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#42]
1) We need to make BIKE and WALK mutually exclusive modes (e.g., the OTP routing engine will find walk legs on a BICYCLE,TRANSIT trip, when needed, so no need to have WALK as an added mode).

2) The form has to be wicked smart when switching between bike and walk modes, especially with the walk/bike distance.  Right now, the MOD Map is using 1/4 mile regardless of WALK or BICYCLE or WALK,BICYCLE modes.  Also, the name of the form should change from 'MAXIMUM WALK' to  'MAXIMUM BIKE'.

3) For example, take a look at the ride.trimet.org form:

https://ride.trimet.org/?mode=BICYCLE,TRANSIT
![bike](https://user-images.githubusercontent.com/64323/34858377-e452c9ba-f704-11e7-8c89-151f911f6703.png)

vs.

https://ride.trimet.org  
![walk](https://user-images.githubusercontent.com/64323/34858369-d6c4aaac-f704-11e7-8e02-2d01f36df0d7.png)

You'll see that 'Maximum walk' goes from 3 miles to 3/4 mile depending on BIKE vs WALK modes.  Further, the form name 'Maximum walk' switches to  'Maximum bike'.  One last subtly is that  if the customer changes his max walk distance, that value is remembered when switching back and forth between walk and bike modes.

**Comment by fpurcell** [comment]
Note: we also need to make the Bike or Walk options disappear if we're in opposite mode, respectively.  For example, the trip modes exclude bike in this state, so the form should not show 'Bicycle Speed' options:
![screen shot 2018-01-17 at 8 41 25 pm](https://user-images.githubusercontent.com/64323/35081160-25a5c9dc-fbc7-11e7-8c04-6515cff359a5.png)

**Comment by demory** [comment]
Addressed in https://github.com/opentripplanner/otp-react-redux/commit/124cf2f79f9b5a672ddf5d291a52fa9881c3b461

Mode-specific parameters (i.e. walk/bike speed/distance) should only appear when associated mode is selected in mode selector. Walk/bike distance/speed have different options and default values.

**Comment by fpurcell** [comment]
Looks good.
