### ISSUE TITLE
UI: For legs with one stop (like on an interline), don't list the stops on the "Ride 1 min, 1 stops" drop down.

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#45]
If a leg only has 1 stop, don't show that "Ride 1 min, 1 stops" drop down.

![interlines](https://user-images.githubusercontent.com/64323/34860473-7b2e4578-f712-11e7-9660-bf1be18f7210.png)

NOTE: I don't think we really need the separate Trip Viewer button and view (at minimum will need a way to turn that off as a config option in config.yml).

**Comment by msrichardson** [comment]
This item was resolved with the 20180202 update.
