### ISSUE TITLE
MAP: trip route geometry has to follow the streets / can't overlap or intersect other lines at strange angles

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#46]
I like the look of the transitive route lines, except when the line is simplified and it cuts across other route geometries, or doesn't follow the road.  The criss-crossing geometry here is confusing on first look. 

![strange overlapping geometry](https://user-images.githubusercontent.com/64323/34860741-76b7a3d4-f714-11e7-9014-c7bb3795d4f7.png)

**Comment by demory** [comment]
Fixed in https://github.com/conveyal/transitive.js/commit/da5320f86694071c562f5f00295ad1231a7dbed5

**Comment by msrichardson** [comment]
This issue has been resolved in the 20180209 update
