### ISSUE TITLE
MAP: route geometries not following the road are just strange

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#47]
![screen shot 2018-01-11 at 9 24 57 pm](https://user-images.githubusercontent.com/64323/34861056-c2008a84-f716-11e7-99c4-214c6e8bc96e.png)

![screen shot 2018-01-11 at 9 22 34 pm](https://user-images.githubusercontent.com/64323/34861060-c729bb5c-f716-11e7-97c5-258db2cd22e8.png)

![strange overlapping geometry](https://user-images.githubusercontent.com/64323/34861063-ca82d8e2-f716-11e7-9389-286d92de46a2.png)

**Comment by fpurcell** [comment]
see #18

**Comment by fpurcell** [comment]
see #46

**Comment by demory** [comment]
Fixed in https://github.com/conveyal/transitive.js/commit/da5320f86694071c562f5f00295ad1231a7dbed5

**Comment by msrichardson** [comment]
This issue has been resolved in the 20180209 update
