### ISSUE TITLE
CONFIG / UI: fine-grained ability to turn on/off aspects of the app

### ISSUE THREAD

**Issue by fpurcell** [conveyal/trimet-mod-otp#49]
Via config.yml, we need the ability to turn on & off the following features: 

- the map's 'Network View' button (such a config would also hide the companion radio button 'Map View')
![screen shot 2018-01-17 at 8 46 06 pm](https://user-images.githubusercontent.com/64323/35081208-8a6bb32c-fbc7-11e7-9d8a-d8f62760152d.png)

- the 'Time Window' (and Profile Routing) options (such a config would also hide the 'Exact Time' companion radio button):
![screen shot 2018-01-17 at 8 47 59 pm](https://user-images.githubusercontent.com/64323/35081239-c5589e14-fbc7-11e7-86e1-8f32a7371a29.png)

- Bike & Walk Speed drop downs under modes -> general option drop-down
![screen shot 2018-01-17 at 8 41 25 pm](https://user-images.githubusercontent.com/64323/35081259-e1e6d618-fbc7-11e7-95d2-44b155f5f4d0.png)

**Comment by msrichardson** [comment]
[https://github.com/conveyal/trimet-mod-otp/issues/64](url)

**Comment by msrichardson** [comment]
Also see #64

**Comment by fpurcell** [comment]
We have configs now that turn off Network View and Time Window ... I'm going to lower this priority down to "Low", since we may still want some other on/off options.

**Comment by fpurcell** [comment]
We have a lot of config control, and will add more where needed on a case by case basis.
