### ISSUE TITLE
Bug: "Recently Searched" Origin/Destination

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#58]
Selecting locations from the 'Recently Searched' list under either origin or destination does not work consistently (sometimes nothing happens upon selecting from the list).

**Comment by landonreed** [comment]
@msrichardson, I think this issue might no longer be relevant given the most recent work. Can you verify that this is working consistently now?

**Comment by msrichardson** [comment]
@landonreed I did some limited testing last week, and it appears to be working, but have left open for time-being to be safe.

**Comment by msrichardson** [comment]
As noted in Oct, the above issue does appear to be resolved, but a new item has cropped up, which may be related to the new clear functionality added to the origin/destination fields.

If you plan some trips with varying start/end points, then plan a trip selecting from the Recently Searched list, the origin/destination will sometimes blank out.  The trip will still plan, but the origin and/or destination won't always show in those fields.  It looks like this might also apply to Nearby Stops.

This issue appears to be isolated to desktop.

**Comment by msrichardson** [comment]
Actually, upon further testing, it now appears that once you have a trip, and you go to change the start or end point, when you click in whichever field you wish to change (say the origin), it will clear out the other field (destination) in the UI only - the trip will still plan properly with whatever you originally entered in the cleared out field (you just can't see it).  It will even clear out the origin after entering the destination upon your first time using it now.
