### ISSUE TITLE
Copy Changes

### ISSUE THREAD

**Issue by kchanba** [conveyal/trimet-mod-otp#6]
- [x] Change "Plan Your Trip Details" copy to "Plan Trip"
- [x] Change calendar date to 'Leave Now' or 'Today' (smart rendering) on first view (prior to editing).
- [x] Change 'Plan Trip' time/mode settings buttons to both say 'Edit'
- [x] On first 'Options' screen change 'Edit Search' to just say 'Edit'
- [x] Change 'Itinerary' text to some phrase describing the trip
- [x] Change Itinerary view to be sentence case, and include arrows
- [x] Change 'Travel' to 'Onboard' or 'Ride' in the 'Itinerary Details'
- [x] Make sure 'Alerts' text is grammatically correct (i.e. '1 alert' instead of '1 alerts')

**Comment by landonreed** [comment]
@kchanba is the first item's original text that needs to be changed `Plan Your Trip Details` (not `Plan Trip Details`)?
