### ISSUE TITLE
Design:  Itineraries containing Bike Share

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#67]
In the sample itinerary shown below, it is not necessarily obvious that the trip is using bike share (BIKETOWN in this instance).  

  - The hubs have 'Community Corral' tacked on to the place names, but unless you happen to know that is a BIKETOWN hub, there is no other indication.

  - The itinerary header says 'Walk', not even mentioning there is a bike component.  Based on what is displayed for transit trips (ex: Walk to Bus), it seems like it should include the biking portion, such as 'Walk to BIKETOWN Hub'.

  - Consider adding a BIKETOWN symbol/indication somewhere within the itinerary display, such as the upper right corner (similar to if there was a transit component).  This could be either in addition to the above items or in place of them.

![biketown](https://user-images.githubusercontent.com/4853348/35694520-7ad75e0a-0736-11e8-88a7-1dd30d474803.png)

**Comment by fpurcell** [comment]
BTW, in addition to the Walk header design issues that Myleen mentions above, the "Stop Viewer" button has some issues:
  a) the button brings up a blank stop viewer with the title, "Loading Stop..."
  b) is this a "Stop" or a "Rack" or a "Corral" or "Bike <something>"?
