### ISSUE TITLE
Internet Browser Compatibility Issues

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#69]
**Internet Explorer**
*Version 11.0.9600.18893 (Windows 7 Professional)

- Page now renders
- But rendering issues (see below)

**Microsoft Edge**
*Version 41.16299.15.0 (Windows 10)

- Origin/Destination inputs do not work (no autocomplete/dropdown; 'Use Current Location' continues to display as type; does not automatically plan trip after entries in both fields (which makes sense due to lack of dropdown - we've noticed must select from the options to plan a trip while testing in other browsers))
- Selecting 'Use Current Location' causes the page to hang; text box says "Fetching location...", but nothing happens.  [This was via a desktop at work on a Windows 10 machine]
- After planning a trip via the map, then clearing the origin/destination inputs via the 'X', if user tries to plan another trip, the route is displayed incorrectly or not at all.

**Safari (Mac)**
*Version 12.0 (13606.2.11) on High Sierra

- start with a small screen, then enlarge to full screen ... scroll around the map, and you'll see the map has gray areas where tiles don't get rendered

**Comment by msrichardson** [comment]
Re: Edge - most issues still persist, except that the page no longer hangs for the second bullet (pop-up appeared asking if okay to use current location).  Unable to text IE at moment (new computer only has Edge), but presume those issues persist.

**Comment by fpurcell** [comment]
Mac Issues (as of 9/15/2018):
#75

**Comment by fpurcell** [comment]
IE (on 9/25/18) is working pretty well.  But I'm seeing strangeness with this trip on IE: https://modbeta.trimet.org/map/#/?fromPlace=45.53235695057665%2C-122.68750215568803&toPlace=45.527807%2C-122.677488&date=2018-09-25&time=15%3A54&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CBICYCLE_RENT&showIntermediateStops=true&maxWalkDistance=4828&optimize=SAFE&bikeSpeed=3.58&ignoreRealtimeUpdates=true&companies=

**Comment by msrichardson** [comment]
Additional IE issues:

1. Lines missing in itinerary narrative
![croppercapture 281](https://user-images.githubusercontent.com/4853348/46223862-69af0580-c309-11e8-8824-aca04c638eb4.png)

2. Alignment issues in Stop Viewer
![croppercapture 282](https://user-images.githubusercontent.com/4853348/46223905-8b0ff180-c309-11e8-980d-32c4a24e2ddc.png)

**Comment by msrichardson** [comment]
**Edge** version 41.16299.666.0 (Windows 10)

_Conveyal test app_:  Map and origin/destination dropdowns not loading (can still technically plan trips by clicking on map frame (although you can't see where you are clicking), or by using current location/nearby stops, but cannot otherwise set your origin/destination)

![87927f5f-bb5b-496a-9f1f-25c5afb6984e](https://user-images.githubusercontent.com/4853348/46424761-d867d680-c6ee-11e8-8091-a1f9c54dd360.png)

![cd401aa5-4e3d-4d5e-b562-52cd2477b284](https://user-images.githubusercontent.com/4853348/46424766-dd2c8a80-c6ee-11e8-8ae7-6e0152b091b6.png)

**Comment by msrichardson** [comment]
Ah, sorry, I left off a key piece of info.  It is 16 (Microsoft EdgeHTML 16.16299).

**Comment by landonreed** [comment]
Strange, I still can't reproduce this one (video: https://saucelabs.com/beta/tests/13b6dc6706ca42a1ac23efe50982f729/watch)

![image](https://user-images.githubusercontent.com/2370911/46432974-9dc96280-c71d-11e8-89b6-f29b5c6e412d.png)

**Comment by msrichardson** [comment]
It occurred for at least two of us.  I'll try this evening on my personal PC (as maybe it is something on our network??).

Also, I did note that the non-HTML version was slightly different (not sure if that would make a difference  or not...)  41.16299.666.0 v 41.16299.15.0

**Comment by msrichardson** [comment]
FWIW, here is the version for the other person I mentioned:
Microsoft Edge 41.16299.611.0
Microsoft EdgeHTML 16.16299

**Comment by landonreed** [comment]
I can't seem to reproduce this issue with this other version of Edge (see below) and unfortunately, there isn't a good way for me to reproduce the exact version number you are running.

Do you know if your system running an out-of-date version of Edge?

![image](https://user-images.githubusercontent.com/2370911/46488984-13ced780-c7b9-11e8-857f-9643b9a535c1.png)

**Comment by msrichardson** [comment]
Sorry for not posting earlier...  I tried it at home, and it worked there, so I tried two different computers at work, and found the same issue as yesterday.  As such, I'm starting to think it is something on our end (plus, the two work computers had two different versions:  41.16299.666.0/16.16299 and 42.17134.1.0/17.17134).

I'll let you know what I find out.

**Comment by msrichardson** [comment]
Re: Edge, it does appear to be an issue on our end.  We are working to implement a fix; will test/provide update that has occurred.

To the best of my knowledge, the IE issues noted on approximately Sept 28 are still pending.

**Comment by msrichardson** [comment]
The Edge issue was on our end and has been resolved.

**Comment by landonreed** [comment]
@fpurcell, can you elaborate on the weirdness you mentioned in https://github.com/conveyal/trimet-mod-otp/issues/69#issuecomment-424529308? On the current version everything looks OK to me in IE.

**Comment by landonreed** [comment]
OK, I believe I have fixed all of the issues documented here. However, I just noticed an issue with selecting an item from the location search dropdown, so I will work on that now. @msrichardson, please let me know if there's anything else outstanding in this ticket. Thanks!

**Comment by landonreed** [comment]
OK, https://github.com/opentripplanner/otp-react-redux/commit/a7ea7ec6d57534d9b7bb444f195659fdbe922452 fixes the location search selection issue in IE. I think that concludes the items here as far as I can tell.

**Comment by msrichardson** [comment]
@landonreed  Re: **Edge** - Every once in a while, some to all of the lines in the itinerary narrative (that correspond with the lines on the map) don't display for the best bet, but if you click another option then come back, they do.  I haven't been able to make this happen consistently, so unsure what may be causing.  (This was tested after latest update today.)  Else, all other items noted above for Edge have been resolved.

Re: IE - as far as this thread goes, the items look to be resolved (may have found a new bug, but will document in new ticket if that is the case).

Waiting for confirmation (on this end) that Safari items resolved, then will close ticket.  Thanks!
