### ISSUE TITLE
Date/Time selector (date persistence issue)

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#74]
If customer changes date (and time) from default, but then changes back to 'Now', the date doesn't update, rather the 'changed' date persists.

For example:

Changed from NOW to DEPART at 7 AM on  5/26/18
![croppercapture 239](https://user-images.githubusercontent.com/4853348/40440488-18e581ce-5e73-11e8-9e13-4fdcdcfa95e3.png)

Changed back to NOW (which would be about 10:22 AM on 5/23/18) - note how it still says 'Saturday' in the tab as opposed to 'Today'.
![croppercapture 241](https://user-images.githubusercontent.com/4853348/40440526-2c18b4f0-5e73-11e8-927d-aad0742ad70f.png)

(and here is view to show that the while the time updated properly, the 'changed' date is persisting)
![croppercapture 242](https://user-images.githubusercontent.com/4853348/40440620-6ec1af14-5e73-11e8-960c-281be8f0a477.png)

This also happens if use the ARRIVE option.

**Comment by fpurcell** [comment]
You can also clean out a date via an **X** option ![image](https://user-images.githubusercontent.com/64323/44180767-224f1b80-a0b3-11e8-929f-15dabc1737a1.png), and then switch back to "Now".

But the cleared out date will prevent you from planning a trip until you select a new date. I'd say, when you select "Now", that would reset the date back to *today*.

**Comment by msrichardson** [comment]
Resolved
