### ISSUE TITLE
Bug: Bike Station and Zipcar map layers

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#80]
1.  The Bike Station layer will not draw unless the user has selected Biketown as a mode (this is especially problematic on the mobile platform)

2.  The Zipcar layer is not drawing on mobile (tested on both iPhone and Android)

**Comment by landonreed** [comment]
Hi @msrichardson, I believe @demory has addressed item 1 recently, but I'm having trouble replicating the issue with the Zipcar display on my Android device.  Could you confirm that the issue is still present and share more info on the OS and browser version used on the mobile devices?

**Comment by msrichardson** [comment]
@landonreed I was actually going to provide an update today!  Yes, the Biketown aspects appear to be fixed.  

As to Zipcar, a couple folks tried it yesterday and it worked for them, but I'm still not having success.  The iphone OS is 11.4.1 and browser is Safari (sorry, having a hard time finding the version).  The android is 8.0.0, SM-G935V Build/R16NW; browser is Chrome, version 68.0.3440.91.

**Comment by landonreed** [comment]
@msrichardson, I forgot to also ask what the device models were (i.e., iPhone 6, Samsung Galaxy, etc.).

**Comment by msrichardson** [comment]
Oh sorry, they are Samsung Galaxy 7 Edge (Samsung-SM-G935V) and an iPhone 8.

**Comment by landonreed** [comment]
Strange -- I'm still unable to reproduce the issue using simulators.  I don't quite have access to the exact Android version/device, but every device I've tried seems to display the Zipcar locations correctly.  Could you post a screenshot of what you see when you try to turn on the layer?  Do they just not appear?

**Comment by msrichardson** [comment]
They just don't appear.  I've also cleared my cache to ensure that isn't the issue.

**Comment by msrichardson** [comment]
@landonreed  Here are the results from others:

1. The first time I loaded trimet-mod-dev.conveyal.com, clicking the zipcar layer did not work. However, I refreshed the page (which caused the checkbox to uncheck itself), then clicked on the layer and it worked.
--> iPhone 7, iOS 11.4.1, Safari

2.  The Zipcar locations do not show up on my phone consistently (I somehow got the layer to appear once, but have not been able to duplicate it since). 
-->iPhone 5S, iOS 11.4.1, Safari

**Comment by landonreed** [comment]
I wonder if this is rather an issue caused by either an unreliable or restrictive network connection.  There doesn't appear to be any issue caused by the browsers themselves.  Are you connecting to the site via wifi or a cellular data network?  Do you know what the download speed for the network is?

**Comment by msrichardson** [comment]
It appears that is the case (and it is our wifi causing the issue).  Sorry for not thinking of that sooner!

**Comment by landonreed** [comment]
No worries, glad we located the source!
