### ISSUE TITLE
Pedestrian Walk Comfort (OSM Tag Weighting)

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#94]
In addition to the existing weighting options, please provide the ability for:

1. combined weighting rules (for example, when maxspeed = X _and_ sidewalk = Y)

    * It is understood that the existing rules are currently multiplicative, but in order to meet the desired effect when certain conditions exist, the individual items would have to be set overly high with the current options.

2. weighting "missing" tags

    * For example, this would be helpful in penalizing unnamed ways

**Comment by demory** [comment]
Pushed a major update to the `mod-ped-routing` OTP branch that expands this functionality. See updated docs: https://github.com/opentripplanner/OpenTripPlanner/blob/b8bce0ef0dcab6a9218347b246cd7a7464c699a4/docs/Pedestrian-Routing.md
