### ISSUE TITLE
Service Update box

### ISSUE THREAD

**Issue by msrichardson** [conveyal/trimet-mod-otp#95]
Please change the language in the real-time Service Update box (see example below) to something more positive, along the lines of "Your trip results have been adjusted based on real-time information."

This should help alleviate any potential confusion when the adjusted trip ends up being faster than the trip under normal conditions (as shown in the screenshot below).

![image](https://user-images.githubusercontent.com/4853348/45715871-1ccd7100-bb4a-11e8-9c2b-7bad34a58f86.png)

**Comment by msrichardson** [comment]
Sorry for not thinking of this sooner, but could the button label change to 'Ignore service updates'?

**Comment by msrichardson** [comment]
Hadn't come across this before, but also, if the 'normal conditions' would involve what appears to be one of the routes changing from one direction to the other (as in the example below for Line 10), could it only be listed once?

![croppercapture 302](https://user-images.githubusercontent.com/4853348/46552689-4ac3ec80-c890-11e8-8a86-52ad91e6a9c8.png)

**Comment by msrichardson** [comment]
@landonreed I agree that the buttons should change too (thus the comment hiding above 😄; I had failed to go back and add the "apply" version to the comment though, sorry).

By the way, for the second box you have shown above, we have more edits coming (I'm waiting to hear back from some folks), to remove 'service delays' from the text, as we have found that both delays _and_ service running hot can cause a change to the returned itineraries.

**Comment by landonreed** [comment]
Gotcha. If there are more changes, perhaps I'll just wait on those to be added here before making the button change if that's OK.

**Comment by msrichardson** [comment]
Yes, that is okay.  Thanks!

**Comment by msrichardson** [comment]
Sorry for the delay in getting back to you.  We would like to replace the existing Service Update box functionality with a static message as shown below.

![croppercapture 339](https://user-images.githubusercontent.com/4853348/49177951-57e6e000-f303-11e8-9b2f-104cec2799c7.png)

**Comment by msrichardson** [comment]
As noted in Slack on 12/18, please add a yellow box around the latest service update text (in order to emphasize).  Thank you.
